"""Generate the canonical architecture decision record index."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from scripts.adr_registry import iter_adrs
except ImportError:  # pragma: no cover - direct script execution
    from adr_registry import iter_adrs


def render(entries: list[dict[str, str | int]]) -> str:
    lines = [
        "# Architecture Decision Records",
        "",
        "> Generated by `python scripts/gen_adr_index.py`; do not edit by hand.",
        "",
        "| Number | Title | Status | Date | File |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        lines.append(
            f"| ADR-{int(entry['number']):04d} | {entry['title']} | "
            f"{entry['status']} | {entry['date']} | [{entry['path']}]({entry['path']}) |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("docs/architecture"))
    parser.add_argument(
        "--output", type=Path, default=Path("docs/architecture/INDEX.md")
    )
    args = parser.parse_args()
    args.output.write_text(render(iter_adrs(args.root)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
